require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NailSalonsController do

  # This should return the minimal set of attributes required to create a valid
  # NailSalon. As you add validations to NailSalon, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NailSalonsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nail_salons as @nail_salons" do
      nail_salon = NailSalon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nail_salons).should eq([nail_salon])
    end
  end

  describe "GET show" do
    it "assigns the requested nail_salon as @nail_salon" do
      nail_salon = NailSalon.create! valid_attributes
      get :show, {:id => nail_salon.to_param}, valid_session
      assigns(:nail_salon).should eq(nail_salon)
    end
  end

  describe "GET new" do
    it "assigns a new nail_salon as @nail_salon" do
      get :new, {}, valid_session
      assigns(:nail_salon).should be_a_new(NailSalon)
    end
  end

  describe "GET edit" do
    it "assigns the requested nail_salon as @nail_salon" do
      nail_salon = NailSalon.create! valid_attributes
      get :edit, {:id => nail_salon.to_param}, valid_session
      assigns(:nail_salon).should eq(nail_salon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NailSalon" do
        expect {
          post :create, {:nail_salon => valid_attributes}, valid_session
        }.to change(NailSalon, :count).by(1)
      end

      it "assigns a newly created nail_salon as @nail_salon" do
        post :create, {:nail_salon => valid_attributes}, valid_session
        assigns(:nail_salon).should be_a(NailSalon)
        assigns(:nail_salon).should be_persisted
      end

      it "redirects to the created nail_salon" do
        post :create, {:nail_salon => valid_attributes}, valid_session
        response.should redirect_to(NailSalon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nail_salon as @nail_salon" do
        # Trigger the behavior that occurs when invalid params are submitted
        NailSalon.any_instance.stub(:save).and_return(false)
        post :create, {:nail_salon => {}}, valid_session
        assigns(:nail_salon).should be_a_new(NailSalon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NailSalon.any_instance.stub(:save).and_return(false)
        post :create, {:nail_salon => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nail_salon" do
        nail_salon = NailSalon.create! valid_attributes
        # Assuming there are no other nail_salons in the database, this
        # specifies that the NailSalon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NailSalon.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nail_salon.to_param, :nail_salon => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nail_salon as @nail_salon" do
        nail_salon = NailSalon.create! valid_attributes
        put :update, {:id => nail_salon.to_param, :nail_salon => valid_attributes}, valid_session
        assigns(:nail_salon).should eq(nail_salon)
      end

      it "redirects to the nail_salon" do
        nail_salon = NailSalon.create! valid_attributes
        put :update, {:id => nail_salon.to_param, :nail_salon => valid_attributes}, valid_session
        response.should redirect_to(nail_salon)
      end
    end

    describe "with invalid params" do
      it "assigns the nail_salon as @nail_salon" do
        nail_salon = NailSalon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NailSalon.any_instance.stub(:save).and_return(false)
        put :update, {:id => nail_salon.to_param, :nail_salon => {}}, valid_session
        assigns(:nail_salon).should eq(nail_salon)
      end

      it "re-renders the 'edit' template" do
        nail_salon = NailSalon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NailSalon.any_instance.stub(:save).and_return(false)
        put :update, {:id => nail_salon.to_param, :nail_salon => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nail_salon" do
      nail_salon = NailSalon.create! valid_attributes
      expect {
        delete :destroy, {:id => nail_salon.to_param}, valid_session
      }.to change(NailSalon, :count).by(-1)
    end

    it "redirects to the nail_salons list" do
      nail_salon = NailSalon.create! valid_attributes
      delete :destroy, {:id => nail_salon.to_param}, valid_session
      response.should redirect_to(nail_salons_url)
    end
  end

end
